services:
  pg:
    build: ./pg
    container_name: pge1
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"

  backend:
    build: ./backend
    container_name: nodeappe1
    environment:
      PGHOST: pg
      PGPORT: 5432
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - pg
